version: '2'
services:

  generate-x509-certificates:
    user: 999:999
    build: env/php-7.4/
    volumes:
      - certs:/tmp
    command: "sh -c 'test -e /tmp/server.cert || openssl req -x509 -newkey rsa:2048 -keyout /tmp/server.key -out /tmp/server.cert -sha256 -days 3650 -nodes -subj /C=XX/ST=StateName/L=CityName/O=CompanyName/OU=CompanySectionName/CN=CommonNameOrHostname'"

  redis-node-1:
    image: redis:7.0.12
    volumes:
      - certs:/certs:ro
      - ./etc/redis/redis-node.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    depends_on:
      generate-x509-certificates:
        condition: service_completed_successfully
  redis-node-2:
    image: redis:7.0.12
    volumes:
      - certs:/certs:ro
      - ./etc/redis/redis-node.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    depends_on:
      generate-x509-certificates:
        condition: service_completed_successfully
  redis-node-3:
    image: redis:7.0.12
    volumes:
      - certs:/certs:ro
      - ./etc/redis/redis-node.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    depends_on:
      generate-x509-certificates:
        condition: service_completed_successfully
  redis-node-4:
    image: redis:7.0.12
    volumes:
      - certs:/certs:ro
      - ./etc/redis/redis-node.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    depends_on:
      generate-x509-certificates:
        condition: service_completed_successfully
  redis-node-5:
    image: redis:7.0.12
    volumes:
      - certs:/certs:ro
      - ./etc/redis/redis-node.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    depends_on:
      generate-x509-certificates:
        condition: service_completed_successfully
  redis-node-6:
    image: redis:7.0.12
    volumes:
      - certs:/certs:ro
      - ./etc/redis/redis-node.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    depends_on:
      generate-x509-certificates:
        condition: service_completed_successfully

  configure-cluster:
    user: 3523:3523
    build: env/php-7.4/
    env_file: "./.env"
    volumes:
      - certs:/certs
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    command: "bash -c '(redis-cli -a $REDIS_PASSWORD --tls --cacert /certs/server.cert -h redis-node-1 cluster info |grep cluster_state:ok) || (yes yes | redis-cli -a $REDIS_PASSWORD --tls --cacert /certs/server.cert --cluster create $(dig +short redis-node-1):6379 $(dig +short redis-node-2):6379 $(dig +short redis-node-3):6379 $(dig +short redis-node-4):6379 $(dig +short redis-node-5):6379 $(dig +short redis-node-6):6379 --cluster-replicas 1)'"

  php-83:
    user: 3523:3523
    build: env/php-8.3/
    volumes:
      - ../:/src/:ro
      - certs:/certs:ro
    depends_on:
      configure-cluster:
        condition: service_completed_successfully
    env_file: "./.env"

  php-74:
    user: 3523:3523
    build: env/php-7.4/
    volumes:
      - ../:/src/:ro
      - certs:/certs:ro
    depends_on:
      configure-cluster:
        condition: service_completed_successfully
    env_file: "./.env"

volumes:
  certs: {}
